config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'pins#index'
  get "about" => "pages#about"
  get "something_else" => "pages#something_else"
  get "bodhi" => "pages#bodhi"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }

	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	 validates :description, presence: true

	  validates :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins

   validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def home
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Wow... you really pinned me ;)'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'OH YEAH!!!!'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "You can't do that..." if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
      <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Almería', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', about_path %></li>  
        <li><%= link_to 'Something Else', something_else_path %></li> 
        <li><%= link_to 'Bodhi', bodhi_path %></li>
        <% if user_signed_in? %>
             <li><%= link_to raw('<span class="glyphicon glyphicon-flash" aria-hidden="true"></span> New Pin'), new_pin_path %></li>
             <li><%= link_to 'Account Settings', edit_user_registration_path %></li>
             <li><div style= "margin: 7px"><%= link_to 'Sign Out', destroy_user_session_path, class: "btn btn-success btn-default", method: :delete %></div></li> 
            <% else %>
            <li><div style= "margin: 7px"><%= link_to "Log In", new_user_session_path, class: "btn btn-success btn-default" %></div></li>
            <% end %>
      </ul>
        </div>
        </div><!-- /.container --> 
  </nav>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jordan It Up</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-warning") %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/pages/_home.html.erb
<div class='jumbotron center'> 
<h1>Welcome to my WORKING App ;)</h1>
		<p>
			<%= link_to "SIGN UP", new_user_registration_path, class: "btn btn-success btn-lg" %>
		</p>

</div>

app/views/pages/about.html.erb
<h1> About Me </h1>
<div class="well"><p>I'm working on third time's the charm :)</p><p> This is a whole lot of text just talkig about what it means to talk about what it means to talk about what it means to talk about what it means to talk about what it means to talk about what it means to talk about what it means to talk about what it means to talk about what it means to talk about what it means to talk about what it means to talk about what it means to talk about what it means to talk about what it means to talk about what it means to talk about what it means to talk about what it means. </p></div>
<%= link_to "2 Parts", "http://youtubedoubler.com/?video1=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DMmBrepbZji0&start1=0&video2=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DMmBrepbZji0&start2=49&authorName=Jord", class: "btn btn-success btn-lg" %>


<h3 align= "right">This is where I live!</h3>

<iframe align= "right" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6112.487922965281!2d-83.01687236926172!3d40.00299788301854!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88388e99dbc42b0f%3A0x821f1bc1625eb7b2!2s328+W+Lane+Ave%2C+Columbus%2C+OH+43201!5e0!3m2!1sen!2sus!4v1458372320767" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

app/views/pages/bodhi.html.erb
<h1>BODHI</h1>

<center><iframe width="853" height="480" src="https://www.youtube.com/embed/QWtsV50_-p4?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe></center>

app/views/pages/home.html.erb
<div class='jumbotron center'> 
<h1>Welcome to my WORKING App ;)</h1>
 <% if user_signed_in? %>
          Eat my dick :*
     <% else %>
		<p>
			<%= link_to "SIGN UP", new_user_registration_path, class: "btn btn-success btn-lg" %>
		</p>
	<% end %>

</div>

app/views/pages/something_else.html.erb
<%= link_to "CAMELFY", 'https://49.media.tumblr.com/af0c9526dc171269e9537598fe04bb95/tumblr_n8f541jkYs1rpe379o1_500.gif', class: "btn btn-success btn-lg" %> <p></p>

<!-- 16:9 aspect ratio -->
<div class="embed-responsive embed-responsive-16by9">
  <iframe width="854" height="480" src="https://www.youtube.com/embed/FmvU3urYQgI" allowfullscreen></iframe>
</div>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <center><img src="http://getupwithgod.com/wp-content/uploads/GUWG-Baloney.gif" alt="..."></center>
      		<div class="carousel-caption">
        		<h3>This</h3>
    			<p>is similar.</p>
      </div>
    </div>
    <div class="item">
      <img src="http://i.imgur.com/Eb3Pg.jpg" alt="...">
      		<div class="carousel-caption">
      			<h3>King</h3>
    			<p>WZRD</p>
      </div>
    </div>
    <div class="item">
      <center><img src="http://api.ning.com/files/MPEt*AnKhufJXhp5RATRedcKeFUc4KVzEZOKeBiy1oKUoijbw*VrUQ0OhYpbDVNZJ9NQ0NOB*WBfNVCvgFEBEmYs8Izx0KT8/0045.gif" alt="..."> </center>
      		<div class="carousel-caption">
        		<h3>The Reincarnation of</h3>
   				<p>Sean Connery</p>
      </div>
    ...
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/pins/_form.html.erb
<%= form_for(@pin, html: { multipart: true }) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="panel-heading">
    <h3><%= f.label :image %></h3>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="panel-heading">
    <h3><%= f.label :description %></h3>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="panel-body">
  <div class="actions">
    <%= f.submit "Pin Me, Muthafukka!!", class: "btn btn-success btn-sm" %>
  </div>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

    <div id="pins" class="transitions-enabled">
      <% @pins.each do |pin| %>
        <div class="box panel panel-default">
          <%= link_to image_tag(pin.image.url(:medium)), pin %>
         
      <% if current_user && pin.user == current_user %>
            <div class='actions', style= "margin: 4px">
              <%= link_to edit_pin_path(pin) do %>
                <span class="glyphicon glyphicon-pencil"></span>
              <% end %>
              <%= link_to pin, method: :delete, data: { confirm: 'Forreal?' } do %>
                <span class="glyphicon glyphicon-remove"></span>
              <% end %>
            </div>
           <% end %>

          <div class='panel_body', style= "margin: 4px">
          By: <strong><%= pin.user.name if pin.user %></strong></br>
          <%= pin.description %>
            



         </div>
         </div>
  <% end %>
</div>

<center><%= will_paginate @posts, renderer: BootstrapPagination::Rails %></center>

</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>
<div class='row'>
	<div class='col-md-offset-2 col-md-8'>
		<div class='panel panel-default'>
	<div class='panel-heading center'>
<%= image_tag @pin.image.url(:medium) %>
	</div>

<div class='panel-body'>
   <p>By: <strong><%= @pin.user.name if @pin.user %></strong></p>
</p>
<p>
  <%= @pin.description %>
 <% if @pin.user == current_user %>
    <%= link_to edit_pin_path(@pin) do %>
                  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                   <%= link_to @pin, method: :delete, data: { confirm: 'Forreal?' } do %>
                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                <% end %> 
              <% end %>
		<% end %>
		</div>
	</div>
</div>